var cfg=window.EVENT_CONFIG;
function $(s){return document.querySelector(s)} function $$(s){return Array.from(document.querySelectorAll(s))}
var store={get:function(k){try{return JSON.parse(localStorage.getItem('hpe2569:'+k))}catch(e){return null}},set:function(k,v){localStorage.setItem('hpe2569:'+k,JSON.stringify(v))},clear:function(){Object.keys(localStorage).filter(function(k){return k.indexOf('hpe2569:')===0}).forEach(function(k){localStorage.removeItem(k)})}};
async function api(name,payload){var r=await fetch(cfg.apiBase+'/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});var j=await r.json().catch(function(){return{error:'invalid_response'}});if(!r.ok)throw new Error(j.error||'request_failed');return j}
function show(id){$$('.panel').forEach(function(x){x.classList.remove('active')});$('#'+id).classList.add('active');window.scrollTo({top:180,behavior:'smooth'})}
$$('[data-view]').forEach(function(b){b.onclick=function(){show(b.dataset.view)}});
if($('#questionNote')) $('#questionNote').textContent=cfg.questionNote||'';

var params=new URLSearchParams(location.search), qrToken=params.get('checkpoint');
if(qrToken){var f=$('#attendanceForm [name="checkpointToken"]');if(f){f.value=qrToken;show('attendance')}}

$('#registerForm').onsubmit=async function(e){e.preventDefault();var fd=new FormData(e.target);$('#registerMsg').textContent='กำลังบันทึก...';try{var j=await api('seminar-register',{event_code:cfg.code,title:fd.get('title'),first_name:fd.get('firstName'),last_name:fd.get('lastName'),email:fd.get('email'),participant_role:fd.get('role'),consent:fd.get('consent')==='on'});store.set('participantToken',j.participant_token);store.set('person',{title:fd.get('title'),firstName:fd.get('firstName'),lastName:fd.get('lastName'),email:fd.get('email')});$('#registerMsg').textContent='ลงทะเบียนสำเร็จ';renderAdmin()}catch(err){$('#registerMsg').textContent='บันทึกไม่สำเร็จ: '+err.message}};

$('#attendanceForm').onsubmit=async function(e){e.preventDefault();var token=store.get('participantToken');if(!token){$('#attendanceMsg').textContent='กรุณาลงทะเบียนก่อน';return}var cp=new FormData(e.target).get('checkpointToken');try{var j=await api('seminar-attendance',{participant_token:token,checkpoint_token:cp});store.set('attendance',{checkpoint:j.checkpoint});$('#attendanceMsg').textContent='บันทึก '+j.checkpoint+' สำเร็จ';renderAdmin()}catch(err){$('#attendanceMsg').textContent='เช็กอินไม่สำเร็จ: '+err.message}};

function renderTest(target,key,type){var box=$(target);box.innerHTML='';var form=document.createElement('form');cfg.questions.forEach(function(x,i){var q=document.createElement('div');q.className='question';q.innerHTML='<strong>'+(i+1)+'. '+x.q+'</strong><div class="options">'+x.choices.map(function(c,j){return '<label><input required type="radio" name="q'+i+'" value="'+j+'"> '+c+'</label>'}).join('')+'</div>';form.appendChild(q)});var btn=document.createElement('button');btn.className='primary';btn.type='submit';btn.textContent='ส่งคำตอบ';form.appendChild(btn);var out=document.createElement('div');out.className='result';form.appendChild(out);form.onsubmit=async function(e){e.preventDefault();var token=store.get('participantToken');if(!token){out.textContent='กรุณาลงทะเบียนก่อน';return}var fd=new FormData(form),score=0,response={};cfg.questions.forEach(function(x,i){response['q'+i]=Number(fd.get('q'+i));if(response['q'+i]===x.a)score++});try{await api('seminar-submit',{participant_token:token,assessment_type:type,score:score,total:cfg.questions.length,response:response});store.set(key,{score:score,total:cfg.questions.length});out.textContent='บันทึกแล้ว คะแนน '+score+'/'+cfg.questions.length;renderAdmin()}catch(err){out.textContent='ส่งไม่สำเร็จ: '+err.message}};box.appendChild(form)}
renderTest('#pretestBox','pretest','pre');renderTest('#posttestBox','posttest','post');

$('#workshopForm').onsubmit=async function(e){e.preventDefault();var token=store.get('participantToken');if(!token){$('#workshopMsg').textContent='กรุณาลงทะเบียนก่อน';return}var fd=new FormData(e.target);try{await api('seminar-workshop-submit',{participant_token:token,group_name:fd.get('groupName'),prototype_title:fd.get('prototypeTitle'),problem_statement:fd.get('problemStatement'),target_group:fd.get('targetGroup'),tool_summary:fd.get('toolSummary'),innovation_summary:fd.get('innovationSummary'),evidence_url:fd.get('evidenceUrl'),reflection:fd.get('reflection')});store.set('workshop',{submitted:true});$('#workshopMsg').textContent='บันทึกหลักฐาน Workshop สำเร็จ';renderAdmin()}catch(err){$('#workshopMsg').textContent='ส่งไม่สำเร็จ: '+err.message}};

var surveyBox=$('#surveyItems');cfg.survey.forEach(function(s,i){var d=document.createElement('div');d.className='question';d.innerHTML='<strong>'+(i+1)+'. '+s+'</strong><div class="options">'+[5,4,3,2,1].map(function(n){return '<label><input required type="radio" name="s'+i+'" value="'+n+'"> '+n+'</label>'}).join('')+'</div>';surveyBox.appendChild(d)});
$('#surveyForm').onsubmit=async function(e){e.preventDefault();var token=store.get('participantToken');if(!token){$('#surveyMsg').textContent='กรุณาลงทะเบียนก่อน';return}var fd=new FormData(e.target),scores=cfg.survey.map(function(_,i){return Number(fd.get('s'+i))}),avg=scores.reduce(function(a,b){return a+b},0)/scores.length;try{await api('seminar-submit',{participant_token:token,assessment_type:'survey',score:avg,total:5,response:{scores:scores,comment:fd.get('comment')}});store.set('survey',{average:avg});$('#surveyMsg').textContent='บันทึกแบบประเมินแล้ว ค่าเฉลี่ย '+avg.toFixed(2)+'/5';renderAdmin()}catch(err){$('#surveyMsg').textContent='ส่งไม่สำเร็จ: '+err.message}};

$('#checkCertificateStatus').onclick=async function(){var token=store.get('participantToken');if(!token){$('#certStatus').textContent='กรุณาลงทะเบียนบนอุปกรณ์นี้ก่อน';return}$('#certStatus').textContent='กำลังตรวจสถานะ...';try{var j=await api('seminar-certificate-status',{participant_token:token});if(j.certificate_status==='approved'&&j.certificate_no&&j.verification_token){var view='./certificate.html?cert='+encodeURIComponent(j.certificate_no)+'&token='+encodeURIComponent(j.verification_token);$('#certStatus').innerHTML='<strong>อนุมัติใบประกาศแล้ว</strong><br>เลขที่ '+j.certificate_no+'<br><a href="'+view+'" target="_blank" rel="noopener">เปิด E-Certificate / PDF</a>'}else if(j.eligible){$('#certStatus').textContent='ผ่านขั้นตอนที่กำหนดแล้ว แต่ยังรอผู้รับผิดชอบอนุมัติใบประกาศ'}else{$('#certStatus').textContent='ยังไม่ครบเกณฑ์: Pre-test '+(j.steps.pre?'✓':'—')+' • Post-test '+(j.steps.post?'✓':'—')+' • ประเมิน '+(j.steps.survey?'✓':'—')+' • Check-in '+(j.steps.check_in?'✓':'—')}}catch(err){$('#certStatus').textContent='ตรวจสถานะไม่สำเร็จ: '+err.message}};

$('#verifyForm').onsubmit=async function(e){e.preventDefault();var fd=new FormData(e.target);$('#verifyResult').textContent='กำลังตรวจสอบ...';try{var j=await api('seminar-verify',{certificate_no:fd.get('certNo').trim(),verification_token:fd.get('verifyToken').trim()});$('#verifyResult').textContent=j.valid?'ใบประกาศถูกต้อง: '+j.name+' • '+j.certificate_no:'ไม่พบใบประกาศที่ตรงกับข้อมูลตรวจสอบ'}catch(err){$('#verifyResult').textContent='ตรวจสอบไม่สำเร็จ'}};

$('#resetPilot').onclick=function(){if(confirm('ล้าง token และสถานะบนอุปกรณ์นี้?')){store.clear();location.reload()}};
function renderAdmin(){var rows=[['ลงทะเบียน',store.get('participantToken')?'แล้ว':'ยัง'],['เช็กอิน',store.get('attendance')?'แล้ว':'ยัง'],['Pre-test',store.get('pretest')?store.get('pretest').score+'/'+store.get('pretest').total:'-'],['Workshop',store.get('workshop')?'ส่งแล้ว':'-'],['Post-test',store.get('posttest')?store.get('posttest').score+'/'+store.get('posttest').total:'-'],['แบบประเมิน',store.get('survey')?Number(store.get('survey').average).toFixed(2):'-'],['Admin approval','Human Gate']];$('#adminCards').innerHTML=rows.map(function(x){return '<div class="card"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>'}).join('');var ready=store.get('participantToken')&&store.get('attendance')&&store.get('pretest')&&store.get('posttest')&&store.get('survey');if(!ready&&$('#certStatus')){$('#certStatus').textContent='ยังทำขั้นตอนไม่ครบ: '+cfg.certificateRule}}
renderAdmin();